/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Scan } from "./Scan";
import { ScanCountArgs } from "./ScanCountArgs";
import { ScanFindManyArgs } from "./ScanFindManyArgs";
import { ScanFindUniqueArgs } from "./ScanFindUniqueArgs";
import { CreateScanArgs } from "./CreateScanArgs";
import { UpdateScanArgs } from "./UpdateScanArgs";
import { DeleteScanArgs } from "./DeleteScanArgs";
import { Patient } from "../../patient/base/Patient";
import { ScanService } from "../scan.service";
@graphql.Resolver(() => Scan)
export class ScanResolverBase {
  constructor(protected readonly service: ScanService) {}

  async _scansMeta(
    @graphql.Args() args: ScanCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Scan])
  async scans(@graphql.Args() args: ScanFindManyArgs): Promise<Scan[]> {
    return this.service.scans(args);
  }

  @graphql.Query(() => Scan, { nullable: true })
  async scan(@graphql.Args() args: ScanFindUniqueArgs): Promise<Scan | null> {
    const result = await this.service.scan(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Scan)
  async createScan(@graphql.Args() args: CreateScanArgs): Promise<Scan> {
    return await this.service.createScan({
      ...args,
      data: {
        ...args.data,

        patient: args.data.patient
          ? {
              connect: args.data.patient,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Scan)
  async updateScan(@graphql.Args() args: UpdateScanArgs): Promise<Scan | null> {
    try {
      return await this.service.updateScan({
        ...args,
        data: {
          ...args.data,

          patient: args.data.patient
            ? {
                connect: args.data.patient,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Scan)
  async deleteScan(@graphql.Args() args: DeleteScanArgs): Promise<Scan | null> {
    try {
      return await this.service.deleteScan(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Patient, {
    nullable: true,
    name: "patient",
  })
  async getPatient(@graphql.Parent() parent: Scan): Promise<Patient | null> {
    const result = await this.service.getPatient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
